file =open("stupids.txt",'r')
#covert stupids to gems
print(file.read())
file.seek(0)
data=file.read().replace("stupids","gems")
file.close()
file =open("stupids.txt",'w')
file.write("")
file.write(data)
file.close()
file=open("newfile.txt",'w')
file.write(data)
print(data)
file.close()
